### ISSUE TITLE
Blocking assignment causes Cascade to hang

### ISSUE THREAD

**Issue by ynaffitgnay** [eschkufz/cascade#11]
## Overview
**Bug report.** Module with similar structure to [this example ](https://github.com/ynaffitgnay/CascadeBenches/blob/master/bugreports/other_cascade_hang.v) hangs after two clock cycles. Removing the assignment to `new_requests_left` on line 153 (or the conditional dependent upon this var on line 155) causes the display statements to print every cycle, as expected. May be related to [this issue](https://github.com/eschkufz/cascade/issues/9).

**Comment by eschkufz** [comment]
This seems like a zero-time loop as well. The combinational always block reads and writes the variable ```new_requests_left``` and triggers itself indefinitely.
