### ISSUE TITLE
Allow variable offset with $fseek

### ISSUE THREAD

**Issue by ynaffitgnay** [eschkufz/cascade#12]
## Overview
**Feature request.**
Currently, $fseek requires the "off" parameter to be a decimal number. It would be helpful to be able to use a variable to change the offset into a file, like fseek on line 21 [here](https://github.com/ynaffitgnay/CascadeBenches/blob/master/bugreports/fseek_variable_offset.v). I'm currently trying to use file i/o in Cascade as a substitute for the AmorphOS memory interface, and the ability to modify this value is critical.

**Comment by eschkufz** [comment]
Okey doke. Works in simulation and avmm backends. Good luck telling josh he has to figure out a way to make this performant.
