### ISSUE TITLE
Delay support

### ISSUE THREAD

**Issue by vegaluisjose** [eschkufz/cascade#29]
Hey Eric,

Very cool project. I was trying to use delay but I am getting a parse error. Is this feature not implemented?. I also tried to run the regression test called timing and got the same error.

```bash
$ build/tools/cascade -e share/cascade/test/regression/simple/timing_1.v
>>> Parse Error:
>>>   > In share/cascade/test/regression/simple/timing_1.v on line 2:
>>>     syntax error, unexpected #
>>> Caught Signal
Goodbye!
```

Thanks!

**Comment by eschkufz** [comment]
Correct. We don't currently support the use of delays. I have it on my list
of features that I'd like to develop soon, but we don't have a concrete
roadmap in this direction just yet.

**Comment by vegaluisjose** [comment]
Awesome, thanks for the clarification.
