### ISSUE TITLE
Unexpected crash in Cascade from removing a register

### ISSUE THREAD

**Issue by ynaffitgnay** [eschkufz/cascade#8]
## Overview

**Bug report.** Cascade crashes with the following error when a register is not assigned a value inside of an always @(*) block:
> CASCADE SHUTDOWN UNEXPECTEDLY

Code to replicate the crash can be found [here](https://github.com/ynaffitgnay/CascadeBenches/blob/master/bugreports/reg_removal_crash.v). Leaving `rd_mux_sel` declared does not appear to affect the behavior, but whenever `rd_mux_sel` is not assigned a value in the always block, the crash occurs.

**Comment by eschkufz** [comment]
What's happening here is we're assuming the invariant that the event expand pass replaces all always @* blocks with an explicit listing of their dependencies. In this case, there are no dependencies, so we end up in the avmm part of our compilation pipeline with an empty list that we didn't expect to see.

~Ignore previous text. I confused myself.~

**Comment by ynaffitgnay** [comment]
It’s stripped down!

---

Tiffany Yang
M.S. Student
Computer Science
The University of Texas at Austin
713-376-1755

**Comment by eschkufz** [comment]
:/ Too much time looking at code. I rescind my griping.
